# **Task 2: Dataset Practice**
1. Create student dataset  
2. Create salary dataset  
3. Create sales dataset

In [108]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
#from sklearn.metrics import accuracy_score
#Avoid Warnings
import warnings
warnings.filterwarnings('ignore')

In [87]:
#Create student dataset
student_data = {
    
    'Study_Hours':[1,2,3,4,5,6,7,8],
    'Marks':[20,30,40,50,60,70,80,90]

}

student_df = pd.DataFrame(student_data)

student_df

   Study_Hours  Marks
0            1     20
1            2     30
2            3     40
3            4     50
4            5     60
5            6     70
6            7     80
7            8     90

In [88]:
#Create Salary dataset
salary_data =  {
   
    'Experience': [1,2,3,4,5],
    'Salary': [25000,35000,45000,55000,65000]
}

salary_df = pd.DataFrame(salary_data)

salary_df

   Experience  Salary
0           1   25000
1           2   35000
2           3   45000
3           4   55000
4           5   65000

In [89]:
#Create Sales Dataset
#create sales dataset
sales_data = {
    'Month_Number': [1,2,3,4,5],
    'Sales': [20000,25000,30000,35000,40000]
}

sales_df = pd.DataFrame(sales_data)

sales_df

   Month_Number  Sales
0             1  20000
1             2  25000
2             3  30000
3             4  35000
4             5  40000

# **Task 3: Train-Test Split Practice** 
1. Split dataset  
2. Use test_size  
3. Use random_state

# Student Dataset

In [90]:
#Split data
# Features and Label
X = student_df[['Study_Hours']]  # Input/Feature data or Independent variable
y = student_df['Marks']      #Output/Label or Dependent variable

X_train,X_test,y_train,y_test=train_test_split(X,y)    # Train/test Split
print("Training Data")
print(X_train)

print("Testing Data")
print(X_test)
print(" y_Test/Train Split")
print("Training Data")
print(y_train)

print("Testing Data")
print(y_test)

Training Data
   Study_Hours
7            8
5            6
2            3
4            5
3            4
1            2
Testing Data
   Study_Hours
0            1
6            7
 y_Test/Train Split
Training Data
7    90
5    70
2    40
4    60
3    50
1    30
Name: Marks, dtype: int64
Testing Data
0    20
6    80
Name: Marks, dtype: int64

In [91]:
#Use  test size
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2
)

print("X_train size:", len(X_train))
print("X_test size:", len(X_test))
print("y_train size:", len(y_train))
print("y_test size:", len(y_test))

X_train size: 6
X_test size: 2
y_train size: 6
y_test size: 2

In [92]:
#Use random state
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42   #random_state ensures the same data split every time the program runs.
)

print(X_train)
print(X_test)
print(y_train)
print(y_test)

   Study_Hours
0            1
7            8
2            3
4            5
3            4
6            7
   Study_Hours
1            2
5            6
0    20
7    90
2    40
4    60
3    50
6    80
Name: Marks, dtype: int64
1    30
5    70
Name: Marks, dtype: int64

# Salary Dataset

In [93]:
#Feature and Label
A= salary_df[["Experience"]]
b= salary_df["Salary"]


A_train,A_test,b_train,b_test=train_test_split(A,b)    # Train/test Split
print("Training Data")
print(A_train)

print("Testing Data")
print(A_test)
print(" b_Test/Train Split")
print("Training Data")
print(b_train)

print("Testing Data")
print(b_test)

Training Data
   Experience
2           3
4           5
1           2
Testing Data
   Experience
0           1
3           4
 b_Test/Train Split
Training Data
2    45000
4    65000
1    35000
Name: Salary, dtype: int64
Testing Data
0    25000
3    55000
Name: Salary, dtype: int64

In [94]:
#Use  test size
A_train, A_test, b_train, b_test = train_test_split(
    A, b,
    test_size=0.2
)

print("A_train size:", len(A_train))
print("A_test size:", len(A_test))
print("b_train size:", len(b_train))
print("b_test size:", len(b_test))

A_train size: 4
A_test size: 1
b_train size: 4
b_test size: 1

In [95]:
#Use random state
A_train, A_test, b_train, b_test = train_test_split(
    A, b,
    test_size=0.2,
    random_state=42   #random_state ensures the same data split every time the program runs.
)

print(A_train)
print(A_test)
print(b_train)
print(b_test)

   Experience
4           5
2           3
0           1
3           4
   Experience
1           2
4    65000
2    45000
0    25000
3    55000
Name: Salary, dtype: int64
1    35000
Name: Salary, dtype: int64

# Sales Dataset

In [96]:
#Features and Label
M= sales_df[["Month_Number"]]
n= sales_df["Sales"]

M_train,M_test,n_train,n_test=train_test_split(M,n)    # Train/test Split
print("Training Data")
print(M_train)

print("Testing Data")
print(M_test)
print(" n_Test/Train Split")
print("Training Data")
print(n_train)

print("Testing Data")
print(n_test)

Training Data
   Month_Number
1             2
0             1
4             5
Testing Data
   Month_Number
3             4
2             3
 n_Test/Train Split
Training Data
1    25000
0    20000
4    40000
Name: Sales, dtype: int64
Testing Data
3    35000
2    30000
Name: Sales, dtype: int64

In [97]:
#Use  test size
M_train, M_test, n_train, n_test = train_test_split(
    M, n,
    test_size=0.2
)

print("M_train size:", len(M_train))
print("M_test size:", len(M_test))
print("n_train size:", len(n_train))
print("n_test size:", len(n_test))

M_train size: 4
M_test size: 1
n_train size: 4
n_test size: 1

In [98]:
#Use random state
M_train, M_test, n_train, n_test = train_test_split(
    M, n,
    test_size=0.2,
    random_state=42   #random_state ensures the same data split every time the program runs.
)

print(M_train)
print(M_test)
print(n_train)
print(n_test)

   Month_Number
4             5
2             3
0             1
3             4
   Month_Number
1             2
4    40000
2    30000
0    20000
3    35000
Name: Sales, dtype: int64
1    25000
Name: Sales, dtype: int64

# **Task 4: Model Training**
1. Train linear regression model  
2. Use fit()  
3. Train with training data only
# **Task 5: Prediction Practice**
1. Predict test data  
2. Compare actual vs predicted  
3. Print accuracy score

# Student Dataset

In [119]:
#Train Model
model =  LinearRegression()
#Use fit
model.fit(X_train,y_train)
print("Model Training Completd")

#predict test data
y_pred = model.predict(X_test) 
 
print(y_pred)

Model Training Completd
[30. 70.]

In [122]:
#Compare actual vs predicted
S_comparison = pd.DataFrame({
    'Actual': y_test,
    'Predicted': y_pred
})

print(S_comparison)

   Actual  Predicted
1      30       30.0
5      70       70.0

In [120]:
#Print accuracy score
score = model.score(X_test, y_test) 
 
print("Accuracy:", score)

Accuracy: 1.0

# Salary Dataset

In [112]:
#Train Model
model =  LinearRegression()
#Use fit
model.fit(A_train,b_train)
print("Model Training Completd")
#Predict test data
b_pred = model.predict(A_test) 
 
print(b_pred)

Model Training Completd
[35000.]

In [106]:
##Compare actual vs predicted
comparison = pd.DataFrame({
    'Actual': b_test,
    'Predicted': b_pred
})

print(comparison)

   Actual  Predicted
1   35000    35000.0

In [113]:
#Print accuracy score
score = model.score(A_test, b_test) 
 
print("Accuracy:", score)

Accuracy: nan

# Sales Dataset

In [115]:
#Train Model
model =  LinearRegression()
#Use fit
model.fit(M_train,n_train)
print("Model Training Completd")
#predict test data
n_pred = model.predict(M_test) 
 
print(n_pred)

Model Training Completd
[25000.]

In [107]:
#Compare actual vs predicted
comparison = pd.DataFrame({
    'Actual': n_test,
    'Predicted': n_pred
})

print(comparison)

   Actual  Predicted
1   25000    25000.0

In [117]:
#Print accuracy score
score = model.score(M_test, n_test) 
 
print("Accuracy:", score)

Accuracy: nan

# **Task 6: Result Analysis** 
1. Identify good predictions  
2. Identify prediction errors  
3. Explain accuracy meaning

# 1. Identify Good Predictions
| Actual | Predicted |
| ------ | --------- |
| 30     | 30.0      |
| 70     | 70.0      |
If predicted values are very close to actual values, the model predictions are good.

# 2. Identify prediction errors

In [124]:
S_comparison['Error'] = S_comparison['Actual'] - S_comparison['Predicted']

print(S_comparison)

   Actual  Predicted         Error
1      30       30.0 -7.105427e-15
5      70       70.0  0.000000e+00

In [125]:
#Clean output
S_comparison['Error'] = S_comparison['Error'].round(2)

print(S_comparison)

   Actual  Predicted  Error
1      30       30.0   -0.0
5      70       70.0    0.0

| Error Value     | Meaning                   |
| --------------- | ------------------------- |
| `0.000000e+00`  | Perfect prediction        |
| `-7.105427e-15` | Almost perfect prediction |
Model prediction is excellent

In [ ]:
# Accuracy Meaning