**Task 2: CSV Practice** 
1. Create CSV file  
2. Read CSV using Pandas  
3. Print dataset

In [14]:
import pandas as pd

In [15]:
#Read CSV 
data = pd.read_csv("Students.csv")

In [16]:
#print data set
data

     Name  Age  Marks Department        City
0     Anu   20     85         CS       Kochi
1   Rahul   21     90         IT     Calicut
2   Meera   19     88        ECE  Trivandrum
3   Arjun   22     76         ME      Kannur
4    Diya   20     95         CS       Kochi
5   Kiran   21     67        EEE    Thrissur
6   Sneha   19     82         IT    Kottayam
7  Vishnu   22     74        ECE    Palakkad
8   Akhil   20     91         CS   Alappuzha
9    Neha   21     79         ME      Kollam

**Task 3: Column Selection** 
1. Select single column  
2. Select multiple columns  
3. Print specific column values

In [17]:
#Select single column
data["Name"]

0       Anu
1     Rahul
2     Meera
3     Arjun
4      Diya
5     Kiran
6     Sneha
7    Vishnu
8     Akhil
9      Neha
Name: Name, dtype: object

In [18]:
#select multiple columns
data[["Name","Age"]]

     Name  Age
0     Anu   20
1   Rahul   21
2   Meera   19
3   Arjun   22
4    Diya   20
5   Kiran   21
6   Sneha   19
7  Vishnu   22
8   Akhil   20
9    Neha   21

In [19]:
#select specific columns
data["Department"]

0     CS
1     IT
2    ECE
3     ME
4     CS
5    EEE
6     IT
7    ECE
8     CS
9     ME
Name: Department, dtype: object

**Task 4: Row Selection** 
1. Select row using loc  
2. Select row using iloc  
3. Slice rows

In [20]:
#Select row using loc
data.loc[0]

Name            Anu
Age              20
Marks            85
Department       CS
City          Kochi
Name: 0, dtype: object

In [21]:
#select row using iloc
data.iloc[2]

Name               Meera
Age                   19
Marks                 88
Department           ECE
City          Trivandrum
Name: 2, dtype: object

In [22]:
#Slice rows
data.iloc[1:4]

    Name  Age  Marks Department        City
1  Rahul   21     90         IT     Calicut
2  Meera   19     88        ECE  Trivandrum
3  Arjun   22     76         ME      Kannur

**Task 5: Filtering** 
1. Filter marks > 80  
2. Filter city names  
3. Combine conditions

In [23]:
#Filter marks > 80
data[data["Marks"] > 80]

    Name  Age  Marks Department        City
0    Anu   20     85         CS       Kochi
1  Rahul   21     90         IT     Calicut
2  Meera   19     88        ECE  Trivandrum
4   Diya   20     95         CS       Kochi
6  Sneha   19     82         IT    Kottayam
8  Akhil   20     91         CS   Alappuzha

In [24]:
# Filter city names
data[data["City"] == "Kochi"]

   Name  Age  Marks Department   City
0   Anu   20     85         CS  Kochi
4  Diya   20     95         CS  Kochi

In [25]:
#Combine Conditions
data[(data["Marks"] > 80) & (data["City"] == "Kochi")]

   Name  Age  Marks Department   City
0   Anu   20     85         CS  Kochi
4  Diya   20     95         CS  Kochi