**Task 2: Missing Data Practice** 
1. Create dataset with missing values  
2. Detect missing values  
3. Count missing values

In [1]:
import pandas as pd
import numpy as np

In [53]:

data = {
    "Name": ["Anu", "Rahul", "Meera", "Arjun", "Diya",
             "Kiran", "Sneha", "Akhil", "Niya", "Vimal"],

    "Marks": [85, np.nan, 90, 78, np.nan,
              67, np.nan, 88, 92, np.nan],

    "Age": [20, 21, np.nan, 22, 20,
            np.nan, 23, 21, np.nan, 24],

    "City": ["Kochi", "Calicut", np.nan, "Trivandrum", "Kannur",
             np.nan, "Kollam", "Kochi", np.nan, "Malappuram"]
}

df = pd.DataFrame(data)

df

    Name  Marks   Age        City
0    Anu   85.0  20.0       Kochi
1  Rahul    NaN  21.0     Calicut
2  Meera   90.0   NaN         NaN
3  Arjun   78.0  22.0  Trivandrum
4   Diya    NaN  20.0      Kannur
5  Kiran   67.0   NaN         NaN
6  Sneha    NaN  23.0      Kollam
7  Akhil   88.0  21.0       Kochi
8   Niya   92.0   NaN         NaN
9  Vimal    NaN  24.0  Malappuram

In [26]:
#Detect Missing values
df.isnull()

    Name  Marks    Age   City
0  False  False  False  False
1  False   True  False  False
2  False  False   True   True
3  False  False  False  False
4  False   True  False  False
5  False  False   True   True
6  False   True  False  False
7  False  False  False  False
8  False  False   True   True
9  False   True  False  False

In [27]:
#Count Missing Values
df.isnull().sum()

Name     0
Marks    4
Age      3
City     3
dtype: int64

**Task 3: Remove Missing Data** 
1. Drop rows with missing values  
2. Drop columns with missing values

In [28]:
#Drop rows with missing values
df.dropna()

    Name  Marks   Age        City
0    Anu   85.0  20.0       Kochi
3  Arjun   78.0  22.0  Trivandrum
7  Akhil   88.0  21.0       Kochi

In [29]:
#Drop columns with missing values
df.dropna(axis=1)

    Name
0    Anu
1  Rahul
2  Meera
3  Arjun
4   Diya
5  Kiran
6  Sneha
7  Akhil
8   Niya
9  Vimal

**Task 4: Fill Missing Data**
1. Fill with text  
2. Fill with mean value  
3. Fill numeric columns

In [30]:
#Fill with text
df["City"]=df["City"].fillna("Unknown")

In [23]:
df

    Name  Marks   Age        City
0    Anu   85.0  20.0       Kochi
1  Rahul    NaN  21.0     Calicut
2  Meera   90.0   NaN     Unknown
3  Arjun   78.0  22.0  Trivandrum
4   Diya    NaN  20.0      Kannur
5  Kiran   67.0   NaN     Unknown
6  Sneha    NaN  23.0      Kollam
7  Akhil   88.0  21.0       Kochi
8   Niya   92.0   NaN     Unknown
9  Vimal    NaN  24.0  Malappuram

In [32]:
#Fill with mean value
df["Marks"] = df["Marks"].fillna(df["Marks"].mean().round(2))

In [33]:
df

    Name  Marks   Age        City
0    Anu  85.00  20.0       Kochi
1  Rahul  83.33  21.0     Calicut
2  Meera  90.00   NaN     Unknown
3  Arjun  78.00  22.0  Trivandrum
4   Diya  83.33  20.0      Kannur
5  Kiran  67.00   NaN     Unknown
6  Sneha  83.33  23.0      Kollam
7  Akhil  88.00  21.0       Kochi
8   Niya  92.00   NaN     Unknown
9  Vimal  83.33  24.0  Malappuram

In [41]:
#Fill numeric column
df["Age"] = df["Age"].fillna(df["Age"].mean()).round(2)
df

    Name  Marks   Age        City
0    Anu  85.00  20.0       Kochi
1  Rahul  83.33  21.0     Calicut
2  Meera  90.00  22.0     Unknown
3  Arjun  78.00  22.0  Trivandrum
4   Diya  83.33  20.0      Kannur
5  Kiran  67.00  22.0     Unknown
6  Sneha  83.33  23.0      Kollam
7  Akhil  88.00  21.0       Kochi
8   Niya  92.00  22.0     Unknown
9  Vimal  83.33  24.0  Malappuram

**Task 5: Duplicate Handling** 
1. Create duplicate rows  
2. Detect duplicates
3. Remove duplicates

In [48]:
#create duplicate rows
data = {
    "Name": ["Anu", "Rahul", "Meera", "Anu", "Diya",
             "Rahul", "Sneha", "Akhil"],

    "Marks": [85, 78, 90, 85, 67,
              78, 88, 92],

    "City": ["Kochi", "Calicut", "Trivandrum", "Kochi",
             "Kannur", "Calicut", "Kollam", "Kochi"]
}

df1 = pd.DataFrame(data)

print(df1)

    Name  Marks        City
0    Anu     85       Kochi
1  Rahul     78     Calicut
2  Meera     90  Trivandrum
3    Anu     85       Kochi
4   Diya     67      Kannur
5  Rahul     78     Calicut
6  Sneha     88      Kollam
7  Akhil     92       Kochi

In [49]:
#Detect duplicate
df1.duplicated()

0    False
1    False
2    False
3     True
4    False
5     True
6    False
7    False
dtype: bool

In [50]:
#Remove duplicates
df1.drop_duplicates()

    Name  Marks        City
0    Anu     85       Kochi
1  Rahul     78     Calicut
2  Meera     90  Trivandrum
4   Diya     67      Kannur
6  Sneha     88      Kollam
7  Akhil     92       Kochi

**Task 6: Column Operations** 
1. Rename columns  
2. Change data type  
3. Print data types

In [54]:
#Rename columns
df.rename(columns={ "Marks": "Score","Age": "Student_Age"}, inplace=True)
df

    Name  Score  Student_Age        City
0    Anu   85.0         20.0       Kochi
1  Rahul    NaN         21.0     Calicut
2  Meera   90.0          NaN         NaN
3  Arjun   78.0         22.0  Trivandrum
4   Diya    NaN         20.0      Kannur
5  Kiran   67.0          NaN         NaN
6  Sneha    NaN         23.0      Kollam
7  Akhil   88.0         21.0       Kochi
8   Niya   92.0          NaN         NaN
9  Vimal    NaN         24.0  Malappuram

In [55]:
df["Score"] = df["Score"].astype(float)
df

    Name  Score  Student_Age        City
0    Anu   85.0         20.0       Kochi
1  Rahul    NaN         21.0     Calicut
2  Meera   90.0          NaN         NaN
3  Arjun   78.0         22.0  Trivandrum
4   Diya    NaN         20.0      Kannur
5  Kiran   67.0          NaN         NaN
6  Sneha    NaN         23.0      Kollam
7  Akhil   88.0         21.0       Kochi
8   Niya   92.0          NaN         NaN
9  Vimal    NaN         24.0  Malappuram