In [1]:
import pandas as pd

**Task 2: Series Practice** 
1. Create Series  
2. Create Series with custom index  
3. Access Series values

In [2]:
#Create Series
numbers = pd.Series([10, 20, 30, 40])
print(numbers)

0    10
1    20
2    30
3    40
dtype: int64

In [3]:
#create series with custom index
students = pd.Series(
    [85, 90, 78],
    index=["Anu", "Rahul", "Meera"]
)

print(students)

Anu      85
Rahul    90
Meera    78
dtype: int64

In [4]:
#Access series values
print(students["Rahul"])

90

**Task 3: DataFrame Practice**
1. Create DataFrame using dictionary  
2. Print DataFrame  
3. Add one more column

In [5]:
#Create Dataframe using dictionary
data = { 
         "Subject":["Maths","IT","DA"],
         "Marks":[95,90,85]
}

df = pd.DataFrame(data)

In [8]:
#Print DataFrame
df

  Subject  Marks
0   Maths     95
1      IT     90
2      DA     85

In [9]:
#Add one more column
df["Grade"] = ["AA","A","A"]

In [10]:
df

  Subject  Marks Grade
0   Maths     95    AA
1      IT     90     A
2      DA     85     A

**Task 4: Data Access** 
1. Access single column  
2. Access multiple columns  
3. Print specific rows

In [11]:
#Access single column
df["Subject"]

0    Maths
1       IT
2       DA
Name: Subject, dtype: object

In [13]:
#Access multiple column
df[["Subject","Marks"]]

  Subject  Marks
0   Maths     95
1      IT     90
2      DA     85

In [15]:
#Printspecific rows
print(df.loc[0])

Subject    Maths
Marks         95
Grade         AA
Name: 0, dtype: object

**Task 5: Data Information** 
1. Use head()  
2. Use tail()  
3. Use info()

In [17]:
df.head(1)

  Subject  Marks Grade
0   Maths     95    AA

In [18]:
df.tail(2)

  Subject  Marks Grade
1      IT     90     A
2      DA     85     A

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Subject  3 non-null      object
 1   Marks    3 non-null      int64
 2   Grade    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes