In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    "Name": [
        "Anu", "Rahul", "Meera", "Arjun", "Diya",
        "Kiran", "Sneha", "Vivek", "Akhil", "Neha"
    ],

    "Department": [
        "HR", "IT", "HR", "Finance", "IT",
        "Marketing", "Finance", "IT", "HR", "Marketing"
    ],

    "City": [
        "Kochi", "Calicut", "Kochi", "Trivandrum", "Kannur",
        "Kochi", "Calicut", "Trivandrum", "Kannur", "Kochi"
    ],

    "Category": [
        "A", "B", "A", "C", "B",
        "A", "C", "B", "A", "C"
    ],

    "Salary": [
        30000, 50000, 35000, 45000, 52000,
        40000, 47000, 55000, 32000, 42000
    ]
}

df = pd.DataFrame(data)

In [3]:
df

    Name Department        City Category  Salary
0    Anu         HR       Kochi        A   30000
1  Rahul         IT     Calicut        B   50000
2  Meera         HR       Kochi        A   35000
3  Arjun    Finance  Trivandrum        C   45000
4   Diya         IT      Kannur        B   52000
5  Kiran  Marketing       Kochi        A   40000
6  Sneha    Finance     Calicut        C   47000
7  Vivek         IT  Trivandrum        B   55000
8  Akhil         HR      Kannur        A   32000
9   Neha  Marketing       Kochi        C   42000

**Task 2: Sorting Practice** 
1. Sort salary ascending  
2. Sort salary descending  
3. Sort by multiple columns

In [4]:
#Sort salary ascending
df.sort_values("Salary")

    Name Department        City Category  Salary
0    Anu         HR       Kochi        A   30000
8  Akhil         HR      Kannur        A   32000
2  Meera         HR       Kochi        A   35000
5  Kiran  Marketing       Kochi        A   40000
9   Neha  Marketing       Kochi        C   42000
3  Arjun    Finance  Trivandrum        C   45000
6  Sneha    Finance     Calicut        C   47000
1  Rahul         IT     Calicut        B   50000
4   Diya         IT      Kannur        B   52000
7  Vivek         IT  Trivandrum        B   55000

In [5]:
#Sort Salary Decending
df.sort_values("Salary",ascending=False)

    Name Department        City Category  Salary
7  Vivek         IT  Trivandrum        B   55000
4   Diya         IT      Kannur        B   52000
1  Rahul         IT     Calicut        B   50000
6  Sneha    Finance     Calicut        C   47000
3  Arjun    Finance  Trivandrum        C   45000
9   Neha  Marketing       Kochi        C   42000
5  Kiran  Marketing       Kochi        A   40000
2  Meera         HR       Kochi        A   35000
8  Akhil         HR      Kannur        A   32000
0    Anu         HR       Kochi        A   30000

In [7]:
#Sort by multiple Columns
df.sort_values(["Department","Salary"])

    Name Department        City Category  Salary
3  Arjun    Finance  Trivandrum        C   45000
6  Sneha    Finance     Calicut        C   47000
0    Anu         HR       Kochi        A   30000
8  Akhil         HR      Kannur        A   32000
2  Meera         HR       Kochi        A   35000
1  Rahul         IT     Calicut        B   50000
4   Diya         IT      Kannur        B   52000
7  Vivek         IT  Trivandrum        B   55000
5  Kiran  Marketing       Kochi        A   40000
9   Neha  Marketing       Kochi        C   42000

**Task 3: Grouping Practice**
1. Group by department  
2. Group by city  
3. Group by category

In [11]:
#Group by department
df.groupby("Department")["Salary"].mean().round(2)

Department
Finance      46000.00
HR           32333.33
IT           52333.33
Marketing    41000.00
Name: Salary, dtype: float64

In [12]:
#Group by City
df.groupby("City")["Salary"].sum()

City
Calicut        97000
Kannur         84000
Kochi         147000
Trivandrum    100000
Name: Salary, dtype: int64

In [13]:
#Group by Category
df.groupby("Category")["Salary"].count()

Category
A    4
B    3
C    3
Name: Salary, dtype: int64

**Task 4: Aggregation Practice** 
1. Find average salary  
2. Find total salary  
3. Count employees

In [16]:
#Find Average Salary
print("Average:",df["Salary"].mean())

Average: 42800.0

In [17]:
#Find total Salary
print("Sum:",df["Salary"].sum())

Sum: 428000

In [19]:
#Count Employees
print("Employee Count:",df["Name"].count())

Employee Count: 10

**Task 5: Multiple Aggregation** 
1. Find mean  
2. Find max  
3. Find min

In [20]:
 df.groupby("Department")["Salary"].agg(["mean", "max", "min"])

                    mean    max    min
Department
Finance     46000.000000  47000  45000
HR          32333.333333  35000  30000
IT          52333.333333  55000  50000
Marketing   41000.000000  42000  40000

**Task 6: Value Counts** 
1. Count departments  
2. Count repeated values  
3. Analyze category frequency

In [25]:
#Count departments
df["Department"].value_counts()

Department
HR           3
IT           3
Finance      2
Marketing    2
Name: count, dtype: int64

In [26]:
#Count repeated values
df["City"].value_counts()

City
Kochi         4
Calicut       2
Trivandrum    2
Kannur        2
Name: count, dtype: int64

In [ ]:
#Analyze category frequency
df["Categ